<div>
  <input autofocus wire:model.debounce.500ms="search" x-ref="search" type="search"
         placeholder="Search"
         class="w-64 py-2 pl-10 pr-3 rounded-full bg-gray-700 text-sm text-gray-200 focus:outline-none focus:shadow-md focus:ring-2 transition ease-in-out focus:ring-primary-600" />

  <div wire:loading.delay wire:target="search" class="absolute left-0" style="top: -2px;">
    <?xml version="1.0" encoding="utf-8"?>
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
         style="margin: auto; background: none; display: block; shape-rendering: auto;" width="40px"
         height="40px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
      <circle cx="50" cy="50" fill="none" stroke="#dad7d7" stroke-width="5" r="26"
              stroke-dasharray="122.52211349000194 42.840704496667314">
        <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite"
                          dur="0.5555555555555556s" values="0 50 50;360 50 50" keyTimes="0;1">
        </animateTransform>
      </circle>
      <!-- [ldio] generated by https://loading.io/ -->
    </svg>
  </div>

  <div wire:loading.delay.class="hidden" wire:target="search" class="absolute"
       style="top: 10px; left: 10px;">
    <svg class="fill-current w-4 text-gray-500" viewBox="0 0 24 24">
      <path class="heroicon-ui"
            d="M16.32 14.9l5.39 5.4a1 1 0 01-1.42 1.4l-5.38-5.38a8 8 0 111.41-1.41zM10 16a6 6 0 100-12 6 6 0 000 12z" />
    </svg>
  </div>

  @if (strlen($search) > 1)
    <div class="absolute bg-primary-600 rounded w-64 mt-4 shadow-lg z-50">
      <ul class="overflow-y-auto search-list" style="max-height: calc(100vh - 85px)">
        @forelse ( $results as $result)
          <li class="border-b border-primary-700">
            <a href="{{ route('movies.show', $result['id']) }}"
               class="transition rounded hover:bg-gray-700 px-3 py-3 flex items-center">
              @if ($result['poster_path'])
                <img class="mr-2 rounded"
                     src="{{ 'https://image.tmdb.org/t/p/w45' . $result['poster_path'] }}"
                     alt="{{ $result['title'] }}">
              @else
                <div class="w-11 h-16 bg-primary-400 rounded mr-2"></div>
              @endif
              <div>
                <h2 class="text-sm">{{ $result['title'] }}</h2>
                <div class="flex text-xs">
                  <span>
                    <svg xmlns="http://www.w3.org/2000/svg" class="text-yellow-500 w-4"
                         viewBox="0 0 20 20" fill="currentColor">
                      <path
                            d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                    </svg>
                  </span>
                  <span>{{ $result['vote_average'] * 10 }}%</span>
                </div>
                @if (array_key_exists('release_date', $result))
                  <p class="text-xs">
                    {{ \Carbon\Carbon::parse($result['release_date'])->diffForHumans() }}
                  </p>
                @endif
              </div>
            </a>
          </li>
        @empty
          <li class="border-b border-primary-700">
            <p class="px-3 py-3 text-sm">
              No results found for "{{ $search }}"
            </p>
          </li>
        @endforelse
      </ul>
    </div>
  @endif
</div>
